### PR TITLE
SSL fix and 1.5.0

### PR DESCRIPTION
**Pull request by kwilcox**

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
@lukecampbell , can you merge this?   
This DBOFS catalog crawl errors without it:
```
from thredds_crawler.crawl import Crawl
catalog_url = 'https://opendap.co-ops.nos.noaa.gov/thredds/catalog/NOAA/DBOFS/MODELS/201501/catalog.xml'
select = ['.*fields.*']
crawler = Crawl(catalog_url, select=select, debug=True)
```

**Comment by lukecampbell** [comment]
I'm not opposed to SSL no-verify for thredds catalogs, but generally SSL should be verified, and certificates should be up to date. I may come back and add a flag to enable no-verify. Is this an issue with the server certificate or python's SSL implementation?

**Comment by lukecampbell** [comment]
Certificate looks good to me...

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            32:cf:72:7b:24:fe:6a:3b:00:1b:25:61:d9:b3:d5:53
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, O=thawte, Inc., CN=thawte SHA256 SSL CA
        Validity
            Not Before: Jul 17 00:00:00 2015 GMT
            Not After : Jul 16 23:59:59 2017 GMT
        Subject: C=US, ST=Maryland, L=Silver Spring, O=NOAA, OU=CO-OPS, CN=tidesandcurrents.noaa.gov
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
            RSA Public Key: (2048 bit)
                Modulus (2048 bit):
                    00:e1:bb:9a:7d:42:0d:7e:82:64:db:d3:ca:77:e3:
                    4f:bf:30:d1:a7:82:dd:ae:1d:82:71:82:3f:12:99:
                    44:58:af:71:24:1c:72:6b:ce:5a:ea:28:2b:84:74:
                    2f:bf:8d:e6:f9:ab:64:94:0c:24:5a:3b:3a:a2:08:
                    9d:2b:2d:0d:bc:93:5b:35:f3:b8:6f:cb:f6:74:90:
                    17:e1:ad:35:82:3d:90:1b:dc:a3:ab:eb:00:cd:fe:
                    3c:4e:36:6b:7e:56:62:f8:96:47:32:1e:40:a5:92:
                    2c:62:cb:3a:75:2a:e5:9c:a6:5c:de:0c:bc:e5:cd:
                    12:1c:9c:6a:b6:23:83:bd:cd:18:fe:c2:8b:29:62:
                    c4:ce:33:c4:d0:8c:d1:a1:96:61:ac:bb:a3:f6:02:
                    4c:a8:69:b4:50:53:6d:d3:33:a1:a3:96:3c:d1:10:
                    44:8b:0a:dd:45:d2:9e:28:2f:45:5d:9b:0e:1d:ab:
                    cf:cf:d5:ae:55:0e:56:e9:09:ef:fe:4e:cc:86:f3:
                    6d:19:06:9c:37:66:5e:54:8c:a3:aa:c1:37:36:7f:
                    b5:98:74:0b:72:01:a0:19:95:c3:28:94:d8:f7:9a:
                    4a:9a:15:5e:12:ea:37:ee:30:55:b2:8c:34:8e:e5:
                    6e:67:4c:cf:a5:cf:7b:e8:36:5d:a9:35:c0:79:99:
                    04:d3
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Subject Alternative Name:
                DNS:tidesandcurrents.noaa.gov
            X509v3 Basic Constraints:
                CA:FALSE
            X509v3 Certificate Policies:
                Policy: 2.23.140.1.2.2
                  CPS: https://www.thawte.com/cps
                  User Notice:
                    Explicit Text: https://www.thawte.com/repository

            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Authority Key Identifier:
                keyid:2B:9A:35:AE:01:18:38:30:E1:70:7A:05:E0:11:76:A3:CE:BD:90:14

            X509v3 CRL Distribution Points:
                URI:http://tg.symcb.com/tg.crl

            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
            Authority Information Access:
                OCSP - URI:http://tg.symcd.com
                CA Issuers - URI:http://tg.symcb.com/tg.crt

```

**Comment by daf** [comment]
It's not the cert.  Kyle mentioned that it has something to do with this: https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2, https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings, and possibly a miscompiled Python?

@lukecampbell I agree with your approach for a no_verify flag in the API somewhere to make its way to this change.

**Comment by kwilcox** [comment]
PRs accepted

**Comment by lukecampbell** [comment]
if the cert is fine and it's something on the application side, I agree, default should be no-verify, which is unfortunate, but we can't punish clients.

**Comment by lukecampbell** [comment]
@kwilcox This insanity with python and SSL is now PLAGUING MY LIFE!

**Comment by kwilcox** [comment]
All of the `ioos.us` sites just broke for me. Going through an adding `verify=False` now...

https://www.ssllabs.com/ssltest/analyze.html?d=ioos.us&latest

That broken chain is the problem.

**Comment by lukecampbell** [comment]
Yeah, thanks for that. I have to add the intermediate certificates to nginx.

**Comment by lukecampbell** [comment]
I couldn't for the life of me figure out why this is such a PITA.

**Comment by lukecampbell** [comment]
screen shot 2016-08-23 at 3 28 28 pm

**Comment by lukecampbell** [comment]
If anyone ever runs into this in the future:

https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html

and

http://nginx.org/en/docs/http/configuring_https_servers.html

See the section about certificate chains.

**Pull request merged**
