### PR TITLE
Python 3.4 support, Travis CI, setup.py cleanup

### PR DESCRIPTION
**Pull request by kwilcox**

### CODE REVIEW

**Comment by kwilcox** [comment]
Travis passes: https://travis-ci.org/kwilcox/thredds_crawler/builds/87464967

**Comment by kwilcox** [comment]
:smiley:

**Comment by daf** [comment]
:jack_o_lantern:

**Comment by kwilcox** [comment]
@lukecampbell I pushed to PyPI and conda-recipes.  Would you mind activating Travis and adding the badge to the README?

**Comment by kwilcox** [comment]
@lukecampbell poke

**Comment by lukecampbell** [comment]
I wonder why I didn't get notified of this until now. Yeah sure, one sec.

**Pull request merged**
